spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:4200
              - http://127.0.0.1:4200
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true
        add-to-simple-url-handler-mapping: true
      discovery:
        locator:
          enabled: false
      routes:
        - id: ms-user-users
          uri: http://ms-user:8082
          predicates:
            - Path=/api/v1/users/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        - id: ms-user-auth
          uri: http://ms-user:8082
          predicates:
            - Path=/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: false

server:
  port: 8887

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
