package tn.esprit.msassessment.dto.ai;

import java.util.List;

/**
 * Represents a question generated by Ollama.
 */
public record GeneratedQuestion(
    String prompt,
    List<String> choices,
    int correctIndex,
    String difficulty
) {}
